services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    env_file: ".env"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    # command: ["ls", "-al"]
    command: ["npm", "start"]